import { Navbar, Sidebar } from '../../../components/main/navigation'
import '../../globals.css'
import { Inter } from 'next/font/google'
import { Toaster } from "../../../components/ui/toaster"


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="">
      <body className={inter.className}>
      <Navbar/>
      <div className="flex">
      <Sidebar/>
        <div className="w-screen px-10">
          <Toaster />
          {children}
        </div>
      </div>
      </body>
    </html>
  )
}
